### ISSUE TITLE
与 lit-html 的区别和优劣？

### ISSUE THREAD

**Issue by big-camel** [strveJs/strve#7]
另外，为什么还用了虚拟DOM？

**Comment by maomincoding** [comment]
你好，Strve 提供了 与 lit-html 相似的模板语法，都是基于 tagged template 的 HTML 模板引擎。我列举几个可以提一提的 Strve 特性。
比如：

1. 支持虚拟dom，后续可以考虑跨平台；
2. 灵活；
3. 支持JSX语法；
4. 轻量级；
5. 易用；
6. 快速；
7. 代码格式化与代码提示方面，使用JSX语法，用户体验更加友好；
...

近期将更新文档，详细内容可以打开文档体验一下。

【English translation:】

Hello, Stve provides template syntax similar to lit html, both of which are HTML template engines based on tagged templates. I will list a few Stve features that can be mentioned.
For example:
1. Support virtual DOM, and consider cross platform in the future;
2. Flexibility;
3. Support JSX syntax;
4. Lightweight;
5. Easy to use;
6. Fast;
7. In terms of code formatting and code prompts, using JSX syntax makes the user experience more user-friendly;

The document will be updated soon, and you can open the document to experience the detailed content.

**Comment by big-camel** [comment]
没明白用用了模版为啥还要使用虚拟dom，多加一层不影响性能吗

**Comment by maomincoding** [comment]
> 没明白用了模版为啥还要使用虚拟dom，多加一层不影响性能吗

这就是框架的权衡取舍了！
（This is the trade-off of the framework！）
